### ISSUE TITLE
Prepared statement with a parameter throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rileythomp** [ClickHouse/clickhouse-java#2461]
### Steps to reproduce

1. Set up a clickhouse container, I'm running `clickhouse/clickhouse-server:25.2-alpine`. There's a database `test_data`, and it has a table `categories`. See bottom section for the create table statement.

2. I'm using clojure, so I start a repl with
`clj -Sdeps '{:deps {com.clickhouse/clickhouse-jdbc {:mvn/version "0.9.0"}}}'`

3. Try to execute a prepared statement with a string parameter
```
(let [conn (java.sql.DriverManager/getConnection "jdbc:clickhouse://localhost:8123" "default" "")
      stmt (.prepareStatement conn "select * from test_data.categories WHERE test_data.categories.name = ? limit 4")]
    (.setString stmt 1 "African")
    (let [rs (.executeQuery stmt)]
      (while (.next rs)
        (println (.getString rs 1) (.getString rs 2)))))
```

4. This returns 
```
line 1:62 no viable alternative at input 'select*fromtest_data.categoriesWHEREtest_data.categories.name'
Execution error (ArrayIndexOutOfBoundsException) at com.clickhouse.jdbc.PreparedStatementImpl/setString (PreparedStatementImpl.java:197).
Index 0 out of bounds for length 0
```

5. When starting the repl with 0.8.4
`clj -Sdeps '{:deps {com.clickhouse/clickhouse-jdbc {:mvn/version "0.8.4"}}}'`
and running the same code I get the expected results of 
`1 African`

### Error Log or Exception StackTrace

```
line 1:62 no viable alternative at input 'select*fromtest_data.categoriesWHEREtest_data.categories.name'
Execution error (ArrayIndexOutOfBoundsException) at com.clickhouse.jdbc.PreparedStatementImpl/setString (PreparedStatementImpl.java:197).
Index 0 out of bounds for length 0
```

### Expected Behaviour

It returns the expected results, e.g.
```
1 African
```

### Code Example

```clojure
(let [conn (java.sql.DriverManager/getConnection "jdbc:clickhouse://localhost:8123" "default" "")
        stmt (.prepareStatement conn "select * from test_data.categories WHERE test_data.categories.name = ? limit 4")]
    (.setString stmt 1 "African")
    (let [rs (.executeQuery stmt)]
      (while (.next rs)
        (println (.getString rs 1) (.getString rs 2)))))

```

#### Client Configuration
```java

```

#### Environment
* [ ] Cloud
* Client version: 0.9.0
* Language version: Clojure CLI version 1.12.0.1488
* OS: Sequoia 15.3.1

#### ClickHouse Server
* ClickHouse Server version: 25.2.2.39
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
```
CREATE TABLE test_data.categories
(
    `id` Int32,
    `name` Nullable(String)
)
ENGINE = MergeTree
ORDER BY id
SETTINGS allow_nullable_key = 1, index_granularity = 8192
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by chernser** [comment]
Fixed

**Comment by OksiBlack** [comment]
Issue persists in 0.9.1


`
{"@timestamp":"2025-08-12T19:50:07.856","level":"ERROR","@version":"1.0.0-SNAPSHOT","service":"recon-ingestion","component":"org.springframework.boot.SpringApplication","owner":"zzzz","message":"Application run failed","exception":"Index 0 out of bounds for length 0","stacktrace":["java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0","\nat com.clickhouse.jdbc.PreparedStatementImpl.setString(PreparedStatementImpl.java:197)","\n... 2 frames excluded","\nat net.ttddyy.dsproxy.proxy.ProxyLogicSupport.proceedExecution(ProxyLogicSupport.java:72)","\nat net.ttddyy.dsproxy.proxy.StatementProxyLogic.performProxyLogic(StatementProxyLogic.java:208)","\nat net.ttddyy.dsproxy.proxy.ProxyLogicSupport.proceedMethodExecution(ProxyLogicSupport.java:103)","\nat net.ttddyy.dsproxy.proxy.StatementProxyLogic.invoke(StatementProxyLogic.java:119)","\nat net.ttddyy.dsproxy.proxy.jdk.PreparedStatementInvocationHandler.invoke(PreparedStatementInvocationHandler.java:37)","\nat jdk.proxy2.$Proxy148.setString(Unknown Source)","\nat org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:327)","\nat org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:115)","\nat org.flywaydb.community.database.clickhouse.ClickHouseSchema.doExists(ClickHouseSchema.java:46)","\nat org.flywaydb.core.internal.database.base.Schema.exists(Schema.java:55)","\nat org.flywaydb.core.internal.command.DbSchemas.lambda$create$0(DbSchemas.java:94)","\nat org.flywaydb.core.internal.jdbc.PlainExecutionTemplate.execute(PlainExecutionTemplate.java:45)","\nat org.flywaydb.core.internal.command.DbSchemas.create(DbSchemas.java:91)","\nat org.flywaydb.core.Flyway.lambda$migrate$1(Flyway.java:206)","\nat org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:210)","\nat org.flywaydb.core.Flyway.migrate(Flyway.java:188)","\nat org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)","\nat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1873)","\nat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1822)","\n... 22 common frames omitted","\nWrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clickHouseFlywayMigrationInitializer' defined in class path resource [ru//csp/cspd/recon/ingestion/infra/config/clickhouse/ClickHouseFlywayConfig.class]: Index 0 out of bounds for length 0","\nat
`

**Comment by chernser** [comment]
Good day, @OksiBlack !
Would you please create a new issue with SQL example? 

Thanks!

**Comment by rileythomp** [comment]
FWIW it is fixed in 0.9.1 with the example in my repro steps
