### ISSUE TITLE
[JDBC-V2] Type resolution in DBEaver for Arrays

### ISSUE THREAD

**Issue by chernser** [ClickHouse/clickhouse-java#2583]
### Description 

There is a problem resolving Array types like `Array(Nullable(Decimal(9,3)))` in DBeaver 25.2. Possible root cause is how CH Driver sets array type when reading data 

Relates: https://github.com/dbeaver/dbeaver/issues/38742

**Comment by chernser** [comment]
Should be fixed in Dbeaver  25.2.2 
https://github.com/dbeaver/dbeaver/issues/38742#issuecomment-3306346664

**Comment by arhayka** [comment]
@chernser Unfortunately, this was not fixed. We reopened the issue after multiple complaints.

**Comment by chernser** [comment]
Good day, @arhayka ! 
Thank you for telling! 

Is it something driver should fix?

**Comment by arhayka** [comment]
@chernser I hope nothing needs to be changed on the driver side. We’ll try to fix it in DBeaver in the near future.

**Comment by chernser** [comment]
Closing as original issue closed.
